name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.3"
      - run: go mod download
      - run: go vet -v
      - run: go test -v
